# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sujeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('datos', models.TextField()),
                ('rmtc', models.TextField()),
                ('fr', models.TextField()),
                ('his', models.ImageField(upload_to='graf/')),
                ('fa', models.TextField()),
                ('gra', models.ImageField(upload_to='graf/')),
                ('fs', models.TextField()),
                ('grs', models.ImageField(upload_to='graf/')),
                ('fp', models.TextField()),
                ('grp', models.ImageField(upload_to='graf/')),
                ('comp1', models.TextField()),
                ('gr1', models.ImageField(upload_to='graf/')),
                ('comp2', models.TextField()),
                ('gr2', models.ImageField(upload_to='graf/')),
                ('comp3', models.TextField()),
                ('gr3', models.ImageField(upload_to='graf/')),
                ('comp4', models.TextField()),
                ('gr4', models.ImageField(upload_to='graf/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sint.Category')),
            ],
        ),
    ]
