# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sujeto',
            name='sig',
            field=models.ImageField(blank=True, null=True, upload_to='graf/'),
        ),
        migrations.AlterField(
            model_name='sujeto',
            name='comp1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sujeto',
            name='comp2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sujeto',
            name='comp3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sujeto',
            name='comp4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sujeto',
            name='fa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sujeto',
            name='fp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sujeto',
            name='fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sujeto',
            name='fs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sujeto',
            name='gr1',
            field=models.ImageField(blank=True, null=True, upload_to='graf/'),
        ),
        migrations.AlterField(
            model_name='sujeto',
            name='gr2',
            field=models.ImageField(blank=True, null=True, upload_to='graf/'),
        ),
        migrations.AlterField(
            model_name='sujeto',
            name='gr3',
            field=models.ImageField(blank=True, null=True, upload_to='graf/'),
        ),
        migrations.AlterField(
            model_name='sujeto',
            name='gr4',
            field=models.ImageField(blank=True, null=True, upload_to='graf/'),
        ),
        migrations.AlterField(
            model_name='sujeto',
            name='gra',
            field=models.ImageField(blank=True, null=True, upload_to='graf/'),
        ),
        migrations.AlterField(
            model_name='sujeto',
            name='grp',
            field=models.ImageField(blank=True, null=True, upload_to='graf/'),
        ),
        migrations.AlterField(
            model_name='sujeto',
            name='grs',
            field=models.ImageField(blank=True, null=True, upload_to='graf/'),
        ),
        migrations.AlterField(
            model_name='sujeto',
            name='his',
            field=models.ImageField(blank=True, null=True, upload_to='graf/'),
        ),
        migrations.AlterField(
            model_name='sujeto',
            name='rmtc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
