# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sint', '0002_auto_20171119_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sujeto',
            old_name='fr',
            new_name='fr1',
        ),
        migrations.AddField(
            model_name='sujeto',
            name='fr2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sujeto',
            name='fr3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sujeto',
            name='fr4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sujeto',
            name='fr5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
