# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sint', '0003_auto_20171123_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sujeto',
            old_name='fa',
            new_name='fa1',
        ),
        migrations.RenameField(
            model_name='sujeto',
            old_name='fs',
            new_name='fa2',
        ),
        migrations.AddField(
            model_name='sujeto',
            name='fa3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sujeto',
            name='fs1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sujeto',
            name='fs2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sujeto',
            name='fs3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
