# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sint', '0004_auto_20171123_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='sujeto',
            name='comp5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sujeto',
            name='comp6',
            field=models.TextField(blank=True, null=True),
        ),
    ]
