# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sint', '0005_auto_20171202_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='sujeto',
            name='datos1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
