# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sint', '0006_sujeto_datos1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tit', models.CharField(max_length=200)),
                ('dat', models.TextField()),
                ('dat1', models.CharField(blank=True, max_length=200, null=True)),
                ('comp', models.ImageField(blank=True, null=True, upload_to='graf/')),
            ],
        ),
    ]
