# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sint', '0007_comparacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparacion',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sint.Category'),
        ),
    ]
