# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sint', '0008_comparacion_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparacion',
            name='dat1',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
