# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sint', '0009_auto_20171205_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sujeto',
            old_name='fs2',
            new_name='comp7',
        ),
        migrations.RenameField(
            model_name='sujeto',
            old_name='gr1',
            new_name='grp1',
        ),
        migrations.RemoveField(
            model_name='sujeto',
            name='gr2',
        ),
        migrations.RemoveField(
            model_name='sujeto',
            name='gr3',
        ),
        migrations.RemoveField(
            model_name='sujeto',
            name='gr4',
        ),
        migrations.AddField(
            model_name='sujeto',
            name='comp8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sujeto',
            name='comp9',
            field=models.TextField(blank=True, null=True),
        ),
    ]
